#!/usr/bin/ruby
# frozen_string_literal: true

Dir[File.join(__dir__, 'lib', '*.rb')].sort.each { |file| require file }

puts 'uid     name                     group                    home'
puts '======  ======================   ======================   ======================'
Unix.users.each do |u|
  print u.id.to_s.ljust(8)
  print u.to_s.ljust(25)
  print u.group.to_s.ljust(25)
  puts u.home
end

puts
print 'Groups: '
Unix.groups.each { |g| print "#{g} (#{g.id}), " }
puts

puts
puts "Confdir: #{Unix.confdir}"
puts "# Processors: #{Unix.nprocessors}"

Config.logging.file = 'rftps.log'
Config.logging.max_level = 4
Logging.erase
Logging.info('Information')
Logging.warning "Multi-line\nmessages are\nsupported!"
